Fix frontend/sidebarteams
puj44/1ne-esports pull request #46
Opened 2022-04-26 11:15 UTC by puj44

> Sidebarteams
- Combined the two functionalities of players and team for adding/deleting/editing details of teams and players
- Popup for adding and editing team/player details

> frontend/src/admincomponents/sidebarcomponents/SidebarPlayers.js
- Added modal for popup that lists textfields for adding team and player details (name,description)
- Delete button next to players for deleting player information
- list.map() function to iterate through the teams array and display the values from backend call

> backend/controllers/admincontroller.js
- displayAll() - fetches all the teams and players details from database and sends the result
- addPlayer() - If player 4's details are null, it will still set the object id in case of future addition of new player
- updatePlayer() - Updates new received details about teams and players
- delPlayer() - Sets the information of player to null (in case of replacement of new players to this team), For teams database; team document is deleted along with its players that are stored in 'players' database of that team id

2022-04-27 08:05 UTC, drachit631 approved these changes

2022-05-02 05:41 UTC, amovar18 commented on backend/controllers/admincontroller.js
> +const uri = "mongodb+srv://1ne-esports:1ne-esports@cluster0.sakf4.mongodb.net/esports_1ne?retryWrites=true&w=majority";
use environment variable for this and add the env file in gitignore

2022-05-02 05:42 UTC, amovar18 commented on backend/controllers/admincontroller.js
> +    return res.status(400).send(result);
send `403` or `401`, `400` means a bad request.

2022-05-02 05:52 UTC, amovar18 requested changes

2022-05-02 05:52 UTC, amovar18 commented on backend/controllers/admincontroller.js
> +                    const tobeinserted2={'_id':teamid,'name':name,'description':desc,'Player1':pid[0],'Player2':pid[1],'Player3':pid[2],'Player4':pid[3]};
variable scoping `tobeinserted2` not needed reuse `tobeinserted`. use javascript naming convention like `toBeInserted`.

2022-05-02 05:52 UTC, amovar18 commented on backend/controllers/admincontroller.js
> +
avoid empty lines in review

2022-05-02 05:52 UTC, amovar18 commented on backend/controllers/admincontroller.js
> +        if(team.tname!==null && team.tdesc!==null){
Nit use `if(team.tname && team.tdesc)` or better would be
```
const { tdesc, tname} = team;
if(tname && tdesc){}
```

2022-05-02 05:52 UTC, amovar18 commented on frontend/src/AdminComponents/AdminLogin.js
> +                url: 'http://localhost:3000/auth/signin/'+logusername+'/'+logpassword,
bad method if anyone intercepts the password then account credentials will be easy to steal use POST and send the details in body as body is encrypted in https

2022-05-02 06:22 UTC, amovar18 requested changes

2022-05-02 06:22 UTC, amovar18 commented on backend/.env
> +REACT_APP_MONGODB_API_KEY = "mongodb+srv://1ne-esports:1ne-esports@cluster0.sakf4.mongodb.net/esports_1ne?retryWrites=true&w=majority";
didnt do .env ignore properly, this should not be here

2022-05-02 06:22 UTC, amovar18 commented on backend/controllers/admincontroller.js
> +                if(!result){return res.status(400).send("not found");}
send `404` instead of `400`

2022-05-02 06:22 UTC, amovar18 commented on backend/controllers/authenticationcontroller.js
> +    const uri = "mongodb+srv://1ne-esports:1ne-esports@cluster0.sakf4.mongodb.net/esports_1ne?retryWrites=true&w=majority";
bring this from .env file

2022-05-02 06:22 UTC, amovar18 commented on backend/routes/authenticationroutes.js
> +router.post("/signin/:username/:password",auth.authenticate);
change the route since password and username is not coming in url

2022-05-02 06:22 UTC, amovar18 commented on frontend/src/AdminComponents/AdminLogin.js
> +                url: 'http://localhost:3000/auth/signin/'+logusername+'/'+logpassword,
send in body like this
```
axios({
                method: 'POST',
                url: 'http://localhost:3000/auth/signin',
                body:{
                    username: logusername,
                    password: logpassoword,
                },
                withCredentials: true
})

2022-05-02 06:22 UTC, amovar18 commented on backend/controllers/authenticationcontroller.js
> +    const uri = "mongodb+srv://1ne-esports:1ne-esports@cluster0.sakf4.mongodb.net/esports_1ne?retryWrites=true&w=majority";
req.params wont be required now

2022-05-04 06:40 UTC, merged